version: '3.8'

services:
  vieneu-wyoming:
    # 1. BẮT BUỘC dùng image bản GPU
    image: ghcr.io/tritue2011/tts-vietneu-wyoming:gpu-latest
    container_name: vieneu-wyoming
    ports:
      - "10200:10200"
    volumes:
      - vieneu_cache:/root/.cache/huggingface
    restart: unless-stopped
    
    # 2. XÓA DẤU THĂNG (#) ĐỂ KÍCH HOẠT GPU NVIDIA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              
    command: ["--uri", "tcp://0.0.0.0:10200"]

volumes:
  vieneu_cache:
